---
name: Lint Code Base

permissions: read-all

on: pull_request

jobs:
  lint:
    name: Lint Code Base
    permissions:
      statuses: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          FIX_MARKDOWN_PRETTIER: false
          FIX_YAML_PRETTIER: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .github/linters
          VALIDATE_JSCPD: false
          VALIDATE_SHELL_SHFMT: false
