---
name: Lint Code Base

on: pull_request

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .github/linters
          # VALIDATE_ALL_CODEBASE: false
          # VALIDATE_BASH: false
          # VALIDATE_JSCPD: false
          VALIDATE_KUBERNETES_KUBEVAL: false
          # VALIDATE_PYTHON: false
          # VALIDATE_PYTHON_FLAKE8: false
          # VALIDATE_PYTHON_BLACK: false
          VALIDATE_YAML: false
